# Generated by Django 4.0.5 on 2022-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day_finished',
            field=models.BooleanField(default=False, verbose_name='День завершен'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='exercise_finished',
            field=models.BooleanField(default=False, verbose_name='Упражнение завершено'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_finished',
            field=models.BooleanField(default=False, verbose_name='Программа завершена'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week_finished',
            field=models.BooleanField(default=False, verbose_name='Неделя завершена'),
        ),
    ]
