# Generated by Django 4.0.5 on 2022-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_days_day_finished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='exercise',
            new_name='exercises',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='exercise_characteristics',
            new_name='exercises_characteristics',
        ),
    ]
